repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the latest Black version
    hooks:
      - id: black
        exclude: |
          ^zbsync_odoo/odoorpc_repo/.*
          ^odoo/.*
          ^addons_OCA/.*
          ^enterprise/.*
